name: SSH Action
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            ls -al
