name: SSH Action
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - name: Adding Known Hosts
      # run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: log dirs
        run: |
          echo "Root Directory"
          ls -la
          ls -l .
          pwd

      # - name: login again
      #   run: ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: login again
        run: rsync

      - name: log ls -la
        run: ls -la
