name: SSH Action
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - name: Adding Known Hosts
      # run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: log dirs
        run: |
          echo "Root Directory"
          ls -la
          ls -l .
          pwd
          mkdir test1
          cd test1
          mkdir test1
          cd test1
          touch hello222222.txt
          pwd
          ls -la

      # - name: login again
      #   run: ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Deploy with rsync
        run: |
          cd test1
          pwd
          ls -l ~/.ssh
          nano ~/.ssh/known_hosts
          rsync -avz ./test1/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public_html/dev/de-opd-manager/test1/

      - name: log ls -la
        run: ls -la
