name: SSH Action 3
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/authorized_keys
          touch ~/.ssh/known_hosts
          touch ~/.ssh/github-actions

          chmod 700 ~/.ssh
          chmod 700 ~/.ssh/authorized_keys
          chmod 700 ~/.ssh/known_hosts
          chmod 700 ~/.ssh/github-actions

          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo $SSH_PRIVATE_KEY | base64 --decode -i > ~/.ssh/github-actions

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/github-actions

          cat ~/.ssh/github-actions
          cat ~/.ssh/authorized_keys
          cat ~/.ssh/known_hosts

        # ls -la
        # pwd
