name: SSH Action 3
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/authorized_keys
          touch ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 700 ~/.ssh/authorized_keys
          chmod 700 ~/.ssh/known_hosts

          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END

          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

          cat ~/.ssh/config

      - name: Check out the source
        run: ssh staging 'ls -la'

        # ssh -x ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

        ## rsync -avz ./test1/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public_html/dev/de-opd-manager/test1/

        # ssh $SSH_USER@$SSH_HOST

        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

        shell: bash

        # echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
        # cat ~/.ssh/id_rsa
        # git clone git@github.com:iartist93/actions.git
        # ls -la
        # ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

        # ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/github-actions
        # cat ~/.ssh/github-actions
        # cat ~/.ssh/authorized_keys
        # cat ~/.ssh/known_hosts
