name: SSH Action 3
on: push
jobs:
  build1:
    name: Checkout stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build2:
    name: SSH Login Stage
    runs-on: ubuntu-latest
    steps:
      - name: install ssh key
      - run: ls -la
# mkdir -p ~/.ssh
# chmod 700 ~/.ssh
# chmod 600 ~/.ssh/authorized_keys
# ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
# echo ${{ secrets.SSH_HOST }} | base64 --decode -i > ~/.ssh/github-actions
# ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/github-actions
# ls -la
# pwd
